### PR TITLE
smaato exchange connector

### PR DESCRIPTION
**Pull request by mlabour**
I have created a pull request for the Smaato Exchange Connector. I was able to successfully pass the smaato certification at http://dspportal.smaato.com/ 
This is a proposal for the Smaato Exchange Connector.

A few issues to keep in mind:

* Smaato has lots of creative sizes. One will need to configure lots of creatives in bidding_agent_ex.cc. I can make a bidding_agent_ex.cc available for Smaato if needed.

* Smaato sends WINS as GET requests. RTBKIT only allows WINS to be POST requests. This can be easily hacked by changing a few files in RTBKIT or by having NGINX in front of RTBKIT and turning Smaato WIN GET requests into POST requests.

### CODE REVIEW

**Comment by RAttab** [comment]
So what's the state of this PR? Are all relevant parties satisfied with it?

Also, could you explain this hack for supporting POST requests? Is there a way to modify the code to avoid said hack?

**Comment by mlabour** [comment]
@RAttab: As far as I am concerned the code is done. Unless you guys want additional changes.

Re. the hack for supporting post request:
* You could have an NGINX in front of the AdServer that would turn POST into GET requests.
* Or you could change handleHttpHeader and handleHttpPayload in soa/service/json_endpoint.cc as followed:

void
JsonConnectionHandler::handleHttpHeader(const HttpHeader & header)
{
    if (!header.contentType.empty()
        && header.contentType.find("json") == string::npos
        && header.contentType.find("text") == string::npos)
        throw Exception("invalid content type '%s' for JSON",
                        header.contentType.c_str());
    __// if (header.verb != "POST")__
    __//    throwException("invalid verb");__                                                                       
}


void
JsonConnectionHandler::
handleHttpPayload(const HttpHeader & header,
                  const std::string & payload)
{
    Json::Value request;
    const char * start = payload.c_str();
    const char * end = start + payload.length();
    while (end > start && end[-1] == '\n') --end;
    try {
        Json::Reader reader;
        if (!reader.parse(start, end, request, false)) {
       __//cerr << "JSON parsing error" << endl;__                                                       
            doError("parsing JSON payload: " + reader.getFormattedErrorMessages());
       __// return;__
        }
    } catch (const std::exception & exc) {
        doError("parsing JSON request: " + string(exc.what()));
        return;
    }
    addActivity("finishedJsonParsing");
    handleJson(header, request, string(start, end));
}

**Comment by RAttab** [comment]
So the JsonConnectionHandler explicitly checks for POST and throws if any other verb is found. While according to the HTTP spec it's supposedly meaningless to provide a body to a GET request, the real world seems to think otherwise so I don't mind removing those checks from the JsonConnectionHandler or at least being able to disable them.

**Comment by mlabour** [comment]
Hi Remy, I resolved the conflict and merge the latest master into the smaato-exchange-connector branch. You guys should be able to now merge the pull request. Cheers.

**Comment by RAttab** [comment]
Alrighty, we finally have a Smaato exchange connector which should make it a whole lot easier to support the various Smaato users now. Thanks!

I also updated the wiki and I think we should make a post on the mailing list recommending that everyone transitions over to the rtbkit implementation. Let me know if you'd like to do so otherwise I'll do it.

**Comment by mlabour** [comment]
Thanks Remy. I would rather that the post comes from a place of undisputed authority therefore I would rather you do it :)

**Pull request merged**
