### PR TITLE
Merging with main branch.

### PR DESCRIPTION
**Pull request by mayankit**

### CODE REVIEW

**Comment by mayankit** [comment]
Including my changes in master branch.

**Comment by mayankit** [comment]
I have put a node.js based rubicon bidding agent.

**Comment by RAttab** [comment]
Could you describe the content of this pull request and explain why it should be merged? I also invite you to review the pull request guidelines (https://github.com/rtbkit/rtbkit/wiki/Pull-Request-Guidelines).

**Comment by mayankit** [comment]
I added node.js based bidding agent. these bidding agent will work with rubicon. Most of the developer can save time in understanding the whole framework by using thease bidding agents.

**Comment by mayankit** [comment]
I added node.js based bidding agent. these bidding agent will work with rubicon. Most of the developer can save time in understanding the whole framework by using thease bidding agents.

**Comment by RAttab** [comment]
Unless I missed something, this looks like a copy-paste of the nodeagent example but with a different agent config. Also, since we're currently in the process of deprecating the node bindings for agents out of RTBkit in favour of HTTP-based agents so adding another node.js example seems counter-productive.

Instead I recommend you rework your pull request as an example config for Rubicon. An entry in the wiki may be a more suitable format for this kind of example.

**Pull request closed without merging**
